name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: |
          docker build \
            --build-arg MY_JSON_SECRET='${{ secrets.MY_JSON_SECRET }}' \
            -t myapp:latest .
 
